Add error for group creation with email that already exists
vinyldns/vinyldns pull request #1047
Opened 2021-09-09 06:27 UTC by Aravindh-Raju

Changes in this pull request:
- Error message will be displayed when we create a new group with email id that's already used by another group.
- Error message will be displayed when we update the group email id with a new one that's already used by another group.
- The error message would recommend the user to contact the existing group to be added to that group. This would reduce the confusion of having multiple groups with same email id.
- Created a new SQL query to get group by email, Created a function to display the error message, Added new test cases.

2021-09-13 19:25 UTC, remerle requested changes
For backward compatibility, we need to add a configuration flag that can toggle this functionality on and off. Take a look at the existing configuration [here](https://github.com/vinyldns/vinyldns/tree/master/modules/api/src/main/scala/vinyldns/api/config). You should be able to add something like `vinyldns.membership.groups.enforce_unique_email_address` or something similar.

By default, this flag should be set to `false` (again for backward compatibility).

2021-09-13 19:25 UTC, remerle commented on AUTHORS.md
> +- Aravindh Raju
These should be in alphabetical order by last name, so you can move your name up

2021-09-14 04:35 UTC, Aravindh-Raju commented on AUTHORS.md
> +- Aravindh Raju
Sure, I'm working on the configuration. I'll commit the changes once done.

2021-09-17 13:43 UTC, remerle requested changes

2021-09-17 13:43 UTC, remerle commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +  def groupWithSameEmailIdDoesNotExist(emailId: String, emailConf: Boolean): Result[Unit] =
It may be clearer if the parameter `emailConf` was named `enforceUniqueEmailId`

2021-09-17 13:43 UTC, remerle commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +      emailConf: Boolean
It may be clearer if the parameter `emailConf` was named `enforceUniqueEmailId`

2021-09-17 13:43 UTC, remerle commented on modules/docs/src/main/mdoc/faq.md
> +wish you use this feature, you can set "vinyldns.groups.enforce-unique-email-id = false" in the configuration.
For backward compatibility, this feature should be off by default

```suggestion
VinylDNS can be configured to disallow multiple groups with the same email address. We have found that 
supporting multiple groups with the same email address to be confusing to many users when there are ownership questions 
in the future. Therefore, we strongly recommend that VinylDNS deployments utilize this feature. If you wish to use this feature, you can set "vinyldns.groups.enforce-unique-email-id = true" in the configuration.
```

2021-09-17 13:43 UTC, remerle commented on modules/portal/public/templates/notification.html
> +    </div>
I'd prefer we didn't try to check against the text that is returned. If we get around to localizing VinylDNS, then this won't work. Let's leave this change out for now.

2021-09-17 14:33 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +      emailConf: Boolean
Sure, I've made the changes.

2021-09-30 08:44 UTC, closed without merging