Consolidate and configure messages displayed to the user
vinyldns/vinyldns pull request #1051
Opened 2021-09-24 08:44 UTC by Aravindh-Raju

Changes in this pull request:
- Consolidated all the messages displayed to the user in Messages.scala
- Made the messages configurable.

2021-09-24 14:35 UTC, remerle requested changes
As discussed offline, there are some changes we want to make here. There are also some failing tests to consider.

2021-09-30 08:44 UTC, Aravindh-Raju commented
Closing the issue [#1047](https://github.com/vinyldns/vinyldns/pull/1047) since it was merged in this PR to make some additional changes.

2021-12-10 12:26 UTC, Aravindh-Raju commented
> As discussed offline, there are some changes we want to make here. There are also some failing tests to consider.

Made changes as discussed, rebased to latest master and added functional tests.

2021-12-10 19:56 UTC, remerle requested changes

2021-12-10 19:56 UTC, remerle commented on project/Dependencies.scala
> +    "com.github.pureconfig"     %% "pureconfig-cats-effect"         % pureConfigV,
Why are these dependencies being specified again? They are already on line 67-68

2021-12-10 19:56 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlGroupRepository.scala
> +            .map(toGroup(1))
What does this `1` mean here in `map(toGroup(1))`?

2021-12-10 19:56 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlGroupRepository.scala
> +  def getGroupByEmailId(groupEmailId: String): IO[Option[Group]] =
Is this really getting the group by email identifier? It seems to be getting the group by email **address**. I guess it could be argued that the email address is an identifier, but in VinylDNS, identifiers are usually UUIDs/GUIDs, so we may want to avoid confusion and go with `getGroupByEmailAddress(groupEmailAddress: String)`

2021-12-10 19:56 UTC, remerle commented on modules/docs/src/main/mdoc/faq.md
> +you can set "vinyldns.groups.enforce-unique-email-id = true" in the configuration.
Make sure to indicate that this is the API configuration since we also have a configuration for the Portal. It may be worth linking to [the documentation for the configuration](https://www.vinyldns.io/operator/config-api.html).

Also, make sure you include this in the example configuration in the documentation provided by [config-api.md](https://github.com/vinyldns/vinyldns/blob/85577a27f0f0232c8e2aa541a59c8235a85023e7/modules/docs/src/main/mdoc/operator/config-api.md#full-example-config)

2021-12-10 19:56 UTC, remerle commented on modules/core/src/main/resources/reference.conf
> +# Configure Messages. Override existing messages with new messages. Refer Messages.scala file for existing messages
Please make sure you update the example config in the documentation at [config-portal.md](https://github.com/vinyldns/vinyldns/blob/85577a27f0f0232c8e2aa541a59c8235a85023e7/modules/docs/src/main/mdoc/operator/config-portal.md#full-example-config) and [config-api.md](https://github.com/vinyldns/vinyldns/blob/85577a27f0f0232c8e2aa541a59c8235a85023e7/modules/docs/src/main/mdoc/operator/config-api.md#full-example-config)

2021-12-13 07:46 UTC, Aravindh-Raju commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlGroupRepository.scala
> +            .map(toGroup(1))
The 1 here means ***columnIndex***. It retrieves the value of the designated column in the current row of this WrappedResultSet object as a byte array. It's mentioned at the end of the file:
`  def toGroup(colIndex: Int): WrappedResultSet => Group = res => {
    fromPB(VinylDNSProto.Group.parseFrom(res.bytes(colIndex)))
  }`
  
It retrieves the data of the group present in ***columnIndex 1*** that we got as a result while getting group by email and then parses it and returns to us the data.

All the functions that "GET" data from the database uses ***columnIndex 1*** to retrieve the value present in column index 1 as byte array and parse the data. 
For Eg: getGroupByName, getGroups, getZones etc.

| column_index | data |
| ------------- | ------------- |
| 1  | BINARY, 4074 Bytes |

2021-12-13 07:47 UTC, Aravindh-Raju commented on project/Dependencies.scala
> +    "com.github.pureconfig"     %% "pureconfig-cats-effect"         % pureConfigV,
I specified it by mistake, will remove them in the next commit along with other changes.

2021-12-13 09:01 UTC, Aravindh-Raju commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlGroupRepository.scala
> +  def getGroupByEmailId(groupEmailId: String): IO[Option[Group]] =
Done the changes in the new commit.

2021-12-13 11:19 UTC, Aravindh-Raju commented on modules/core/src/main/resources/reference.conf
> +# Configure Messages. Override existing messages with new messages. Refer Messages.scala file for existing messages
I have updated the `enforce-unique-email` config details in [config-api.md](https://www.vinyldns.io/operator/config-api.html) and [faq.md](https://www.vinyldns.io/faq.html). But `messages` configuration is done in `core` module `reference.conf` as discussed before, which was newly created since all the messages can only be imported and used in `core` module and cannot be imported and configured in `api` and `portal` modules. So, where should I mention about `messages` configuration? Should I create a new `config.md` file (eg) config-core.md for `core` module `reference.conf` or just mention about `messages` configuration in [faq.md](https://www.vinyldns.io/faq.html)?

2021-12-13 14:40 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlGroupRepository.scala
> +            .map(toGroup(1))
As a general rule, we want to avoid "magic numbers" (i.e., unnamed numerical constants). As such, we should define a constant such as:
```scala
val DataColumnIndex = 1
```

We can always make more specific constants if there's ambiguity between queries and the `data` column index.

2021-12-13 14:48 UTC, remerle requested changes

2021-12-13 14:48 UTC, remerle commented on modules/core/src/main/resources/reference.conf
> +# Configure Messages. Override existing messages with new messages. Refer Messages.scala file for existing messages
Will the configuration be picked up if it is specified in the `API` and/or `Portal` configurations? If so, then the configuration examples should be added to both the Portal and the API documentation.

2021-12-14 10:30 UTC, Aravindh-Raju commented on modules/core/src/main/resources/reference.conf
> +# Configure Messages. Override existing messages with new messages. Refer Messages.scala file for existing messages
Configuration is now specified in the `API configurations` instead of `core module` and is being picked up. Configuration examples has been added to [config-api.md](https://github.com/vinyldns/vinyldns/blob/306b3273f4574c0b37622cbfb0bc4de7c1eafadc/modules/docs/src/main/mdoc/operator/config-api.md#configure-messages) and has been referred in [faq.md](https://github.com/vinyldns/vinyldns/blob/306b3273f4574c0b37622cbfb0bc4de7c1eafadc/modules/docs/src/main/mdoc/faq.md#11-how-to-configure-messages-displayed-to-the-users-). But it cannot be picked up in `Portal configurations`, Hence did not update there.

2021-12-14 10:33 UTC, Aravindh-Raju commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlGroupRepository.scala
> +            .map(toGroup(1))
Defined a constant `DataColumnIndex` as suggested in every files under the `mysql` module where these "magic numbers" are used and committed the changes.

2021-12-15 15:48 UTC, remerle approved these changes

2023-09-07 05:08 UTC, Aravindh-Raju commented
Closing this as a new PR has been opened: #1291.

2023-09-07 05:08 UTC, closed without merging