Hardcoded limits changed as configurable.
vinyldns/vinyldns pull request #1052
Opened 2021-09-29 04:07 UTC by Jay07GIT

Changes in this pull request:
- Changed the hardcoded limits to configurable from reference.conf
- This changes belongs to only Membership(groups).

2021-09-29 04:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vinyldns/vinyldns?pullRequest=1052) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vinyldns/vinyldns?pullRequest=1052) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vinyldns/vinyldns?pullRequest=1052) it.</sub>

2021-09-29 12:30 UTC, Jay07GIT commented
Completed changes for batch change, zone , recordset for limits as configurable.

2021-12-14 19:53 UTC, remerle requested changes

2021-12-14 19:53 UTC, remerle commented on modules/api/src/main/resources/reference.conf
> +  }
Please update the corresponding [config-api.md](https://github.com/vinyldns/vinyldns/blob/master/modules/docs/src/main/mdoc/operator/config-api.md#full-example-config) to include these.

2021-12-15 11:09 UTC, Jay07GIT commented on modules/api/src/main/resources/reference.conf
> +  }
Updated config-api.md and submitted new [PR](https://github.com/vinyldns/vinyldns/pull/1070)

2021-12-22 13:59 UTC, remerle approved these changes
LGTM 👍

2022-02-07 18:35 UTC, merged