Create transaction to maintain atomicity
vinyldns/vinyldns pull request #1076
Opened 2021-12-20 12:49 UTC by Aravindh-Raju

Refer: GH-1062

Changes in this pull request:
- Created a transaction in the file `ZoneSyncHandler.scala` to maintain atomicity. Now, either both gets executed or none gets executed.
- Verified the transaction by running locally and also by adding tests.

2021-12-21 09:51 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
> +                throw new Exception(e.getMessage + " Rollback completed successfully!")
When there's an exception, if any changes was made to the database it gets into the catch block and rollbacks to the previous state. Also verified this by running locally.

2021-12-21 09:54 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
> +              db.commit() // commit a transaction
Only commits the changes to database when both `saveRecordChanges` and `saveRecordSets` executed successfully, else in case of any exception changes gets rolled back. Thus either both gets executed or nothing gets executed.

2021-12-21 09:55 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
> +                       exceptionNumber: Int = 0
Added a parameter to raise an exception and check the working of transaction.

2021-12-21 09:58 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
> +              if(exceptionNumber == 1) throw new Exception("SaveRecordChanges failed!")
Used in a test below. Raise an exception after `saveRecordChanges` to check whether any changes made before exception gets rolled back.

2021-12-21 09:59 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
> +              if(exceptionNumber == 2) throw new Exception("SaveRecordSets failed!")
Used in a test below. Raise an exception after `saveRecordSets` to check whether any changes made before exception gets rolled back.

2021-12-21 10:01 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
> +            systemMessage = Some(e.getMessage) // check the exception occurred
Get the error message to check whether it gets into the catch block and rolls back any changes made. Used in the test below.

2021-12-21 10:09 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
> +      result.systemMessage.get shouldBe "SaveRecordChanges failed! Rollback completed successfully!"
If there's an exception and it goes to the catch block and the rollback was successful, this should pass. If it doesn't rollback this won't pass.

2021-12-21 10:10 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala
> +      result.systemMessage.get shouldBe "SaveRecordSets failed! Rollback completed successfully!"
If there's an exception and it goes to the catch block and the rollback was successful, this should pass. If it doesn't rollback this won't pass.

2021-12-27 12:16 UTC, Aravindh-Raju commented
Reference using which the changes were made:
- [Transaction management using an automatic session](https://github.com/scalikejdbc/scalikejdbc-cookbook/blob/master/en/04_transaction.md#transaction-management-using-an-automatic-session)
- [#withinTx block / session](http://scalikejdbc.org/documentation/transaction.html)
- [AutoSession to use along withinTX](http://scalikejdbc.org/documentation/auto-session.html)

Removed `localTx` transaction from `MySqlRecordChangeRepository.scala` and `MySqlRecordSetRepository.scala` to wrap them into a `withinTx` transaction in `ZoneSyncHandler.scala` by following the approach [Transaction management using an automatic session](https://github.com/scalikejdbc/scalikejdbc-cookbook/blob/master/en/04_transaction.md#transaction-management-using-an-automatic-session). Now atomicity is maintained and we can also execute them individually as we use [AutoSession](http://scalikejdbc.org/documentation/auto-session.html)

2022-01-05 13:34 UTC, Aravindh-Raju commented
Will provide details regarding how to reproduce the error, screenshots of database changes before and after implementation of transaction along with other places where non-atomic transaction takes place tomorrow.

2022-01-07 15:50 UTC, remerle requested changes
Just a couple of notes

2022-01-07 15:50 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordChangeRepository.scala
> +        changeSet.changes
Are we able to keep the local transactions? Nested transactions should work.

If this method is ever called outside of a transaction then we risk losing atomicity of the batch insert.

2022-01-07 15:50 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
> -        DB.localTx { implicit s =>
Same here.. can we keep this `localTx`?

2022-01-10 12:03 UTC, Aravindh-Raju commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordChangeRepository.scala
> +        changeSet.changes
I will look into using `localTx` nested transaction further. But as I've seen about using nested transactions in `scalikejdbc` there has not been much results related. There's not been enough details about nested transactions using `scalikejdbc` in their official documentation and also in other places. 

If we call this method outside of the transaction created in `zonesynchandler.scala`, it'll create a `readOnly` or `autoCommit` transaction automatically as given [here](https://github.com/scalikejdbc/scalikejdbc-cookbook/blob/master/en/04_transaction.md#transaction-management-using-an-automatic-session). But since it doesn't have rollback like `localTx`, we risk losing atomicity as you said.

Will look further into it and report back here.

2022-01-11 12:43 UTC, Aravindh-Raju commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
> -        DB.localTx { implicit s =>
Updated the PR with some changes. Now, even if the method is called outside of the transaction it’s atomicity is maintained. The code is redundant, but it has a condition such that it identifies if the method is called outside of the transaction and wraps it with localTx. Else, it uses the transaction mentioned outside. Thus maintaining atomicity in both case.

2022-01-11 17:16 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
> -        DB.localTx { implicit s =>
Is it possible to instead have a bit more control over the transaction by controlling the connection itself?

From the caller:

```scala
using(DB(connectionPool.borrow())) { db: DB =>
  // keep the connection open while in this `using` block
  db.autoClose(false)

  db.begin()
  try {
    val saveRecordChanges = time(s"zone.sync.saveChanges; zoneName='${zone.name}'")(
      recordChangeRepository.save(changeSet)
    )
    val saveRecordSets = time(s"zone.sync.saveRecordSets; zoneName='${zone.name}'")(
      recordSetRepository.apply(changeSet)
    )

    // join together the results of saving both the record changes as well as the record sets
    for {
      _ <- saveRecordChanges
      _ <- saveRecordSets
    } yield zoneChange.copy(
      zone.copy(status = ZoneStatus.Active, latestSync = Some(DateTime.now)),
      status = ZoneChangeStatus.Synced
    )
  } catch { case e =>
    db.rollbackIfActive()
    throw e
  }
}
```

Each called method then can use `withinTx` which will fail with an `IllegalStateException` if there is no active transaction.
```scala
def save(db: DB, changeSet: ChangeSet) {
  db withinTx { implicit session =>
    // Do DB work
    changeSet.changes...
    .foreach { group => INSERT...apply() }
  }
}
```

By default, `DB.localTx` borrows a connection from the pool, then "closes" it when the execution is complete. By controlling the connection, we should be able to more cleanly control a transaction that spans repository actions.

2022-01-11 17:18 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordChangeRepository.scala
> +        changeSet.changes
See my latest comment

2022-01-11 17:43 UTC, remerle commented
> AutoSession starts a read-only transaction session for a select statement, and an auto-commit transaction session for update statements when executing individually, and inside a `withinTx` transaction block when executing together. Thus we can now atomically make changes to the database both while executing together and also while executing them individually.

@Aravindh-Raju We want to avoid auto-commit. It can lead to unintended consequences since each statement is committed after it's executed. We want all of the changes made first, then committed **all at once**.

For example, if we have two `UPDATE` statements with auto-commit enabled, then when the first statement executes, it will be committed, then the second could execute and fail. Since the first statement is committed, those changes cannot be rolled back. For more reading, you can check out [this explanation on SO](https://stackoverflow.com/a/2950764/62195).

Take a look at my suggestion here: https://github.com/vinyldns/vinyldns/pull/1076#discussion_r782365440. I don't believe we can avoid introducing lower-level DB calls as much as we'd like to keep them confined to the `Repository` types. We need to prioritize data integrity over design purity. At some point, perhaps we can move to a DB library that has better abstractions

2022-01-12 04:52 UTC, Aravindh-Raju commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala
> -        DB.localTx { implicit s =>
Thanks Ryan, I'll proceed with this and get back once completed!

2022-01-12 04:56 UTC, Aravindh-Raju commented
> > AutoSession starts a read-only transaction session for a select statement, and an auto-commit transaction session for update statements when executing individually, and inside a `withinTx` transaction block when executing together. Thus we can now atomically make changes to the database both while executing together and also while executing them individually.
> 
> @Aravindh-Raju We want to avoid auto-commit. It can lead to unintended consequences since each statement is committed after it's executed. We want all of the changes made first, then committed **all at once**.
> 
> For example, if we have two `UPDATE` statements with auto-commit enabled, then when the first statement executes, it will be committed, then the second could execute and fail. Since the first statement is committed, those changes cannot be rolled back. For more reading, you can check out [this explanation on SO](https://stackoverflow.com/a/2950764/62195).
> 
> Take a look at my suggestion here: [#1076 (comment)](https://github.com/vinyldns/vinyldns/pull/1076#discussion_r782365440). I don't believe we can avoid introducing lower-level DB calls as much as we'd like to keep them confined to the `Repository` types. We need to prioritize data integrity over design purity. At some point, perhaps we can move to a DB library that has better abstractions

Yes, I'll avoid using `auto-commit`. Didn't thought of using it, but could not find any other solution that works without `AutoSession`, therefore have to proceed with that. I'll follow your suggestion given [here](https://github.com/vinyldns/vinyldns/pull/1076#discussion_r782365440) and complete the changes.

2022-01-18 20:20 UTC, remerle requested changes
This is looking good. I just think we need to reduce the code duplication.

Take a look at [the POC I put together](https://github.com/vinyldns/vinyldns/compare/master...remerle:db-tx). It allows better encapsulation of the database transaction without leaking the details of `commit` and `rollback` to the caller.

2022-01-18 20:20 UTC, remerle commented on modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
> +    executeWithinTransaction { db: DB => {
This is a lot of logic to exist within a DB transaction. We should limit the transaction scope to the fewest steps possible to ensure atomicity.

2022-01-18 20:20 UTC, remerle commented on modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
> +        _ <- recordChangeRepository.save(db, changeSet)
You don't need to leave these as separate steps in the `for` comprehension (that way you can limit the scope of the transaction.

2022-01-18 20:20 UTC, remerle commented on modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
> +        ok
We want to avoid needing to handle this for every database transaction. This should all be rolled up into the `executeWithinTransaction` method

2022-01-18 20:20 UTC, remerle commented on modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala
> +  def executeWithinTransaction[A](execution: DB => A): A = {
This should move to its own `trait`

2022-01-19 13:58 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
> +        ok
Completed the changes in the latest commit.

2022-01-19 13:58 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
> +        _ <- recordChangeRepository.save(db, changeSet)
Followed the POC and made the changes.

2022-01-19 13:58 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
> +    executeWithinTransaction { db: DB => {
Followed the POC and made the changes accordingly.

2022-01-19 23:55 UTC, remerle reviewed
This looks good! Thanks @Aravindh-Raju 

I think we should just include the changes to the `batch_change`/`single_change` tables as noted in my one comment below.

2022-01-19 23:55 UTC, remerle commented on modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
>        _ <- batchChangeRepository.updateSingleChanges(singleChangeStatusUpdates)
Should all of these changes happen in the same transaction? 🤔

2022-01-20 08:26 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
>        _ <- batchChangeRepository.updateSingleChanges(singleChangeStatusUpdates)
Yes, these should happen in same transaction. Because when there’s an exception while updating the `single-change`, recordset and recordset-change will already be `saved to database` and displayed in the respective zone as `completed`, but the batch status will be in `Pending Processing` and SQS keeps retrying to update the single change operation that failed. Therefore in DNS Changes page of our portal, the batch status will be shown as `Pending Processing`. But when we go to the respective zone the records belongs to, it will be displayed as completed or when we search in RecordSet Search the records will be displayed and they’re also stored in DB. This shouldn't happen.

If we keep them all in a single transaction, and update `single-change` fails, everything will be rollbacked and won’t be displayed anywhere until everything (save recordset, recordset-change, update single-change) is executed without any error. When error occurs nothing will be saved and SQS retries with `Pending Processing` until everything is executed without errors.

I’ve made the changes and updated the PR with everything wrapped in the same transaction to ensure proper working and maintaining atomicity. Checked the working in quickstart and it works as expected.

2022-01-27 17:07 UTC, remerle approved these changes
I think this puts us in much better shape with respect to atomicity. 👍

2022-01-31 22:46 UTC, merged