Update for recordset_data table based on rsdump
vinyldns/vinyldns pull request #1092
Opened 2022-03-04 10:02 UTC by Jay07GIT

### Changes in this pull request:

- Update for `recordset_data` table based on `rsdump`

2022-03-07 07:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vinyldns/vinyldns?pullRequest=1092) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vinyldns/vinyldns?pullRequest=1092) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Jay07GIT<br/>:x: jvelku299<br/><hr/>**jvelku299** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vinyldns/vinyldns?pullRequest=1092) it.</sub>

2022-03-08 12:50 UTC, remerle requested changes

2022-03-08 12:50 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
> +  def insert(
The method name `insert` is not descriptive enough. Maybe `insertRecordSetData`?

2022-03-08 12:50 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
>    def getRecordSetDatas(zoneId: String, typ: RecordType): IO[List[RecordSet]] =
As an aside, `data` is already plural, so `datas` is not a word. This could be `getRecordSetDataList` to indicate the plurality.

2022-03-09 04:13 UTC, Jay07GIT commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
>    def getRecordSetDatas(zoneId: String, typ: RecordType): IO[List[RecordSet]] =
Modified `getRecordSetDatas` to `getRecordSetDataList` as suggested.

2022-03-09 04:15 UTC, Jay07GIT commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
> +  def insert(
Modified `insert` to `insertRecordSetData` as suggested.

2022-03-09 04:15 UTC, Jay07GIT commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
> +             ): String = {
Modified `record` to `extractRecordSetDataString` as suggested.

2022-03-09 14:33 UTC, remerle approved these changes

2022-03-09 15:22 UTC, merged