Allow Users to View Members of Other Groups
vinyldns/vinyldns pull request #1097
Opened 2022-03-11 19:52 UTC by nspadaccino

All logged in users can now view the group details of any group, not just groups they are part of. This allows users to see the members and admins of other groups without reaching out to support. This is read-only, users still cannot modify groups they are not part of.

Resolves https://github.com/vinyldns/vinyldns/issues/1088

2022-03-14 09:17 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
>        }
Since it has `TODO`, Is this test completed? If so, can we remove the comments?

2022-03-14 09:17 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipValidations.scala
> +      authPrincipal.isGroupMember(groupId) || authPrincipal.isSystemAdmin || true
Everything looks fine and works as expected locally. 
Just a thought, wouldn’t it be good to have a variable something like `private val viewGroupDetails = true` which we can use here as:
`authPrincipal.isGroupMember(groupId) || authPrincipal.isSystemAdmin || viewGroupDetails` instead of true. So that we can know what’s the `true` is for when we revisit the code later.

2022-03-14 14:06 UTC, nspadaccino commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipValidations.scala
> +      authPrincipal.isGroupMember(groupId) || authPrincipal.isSystemAdmin || true
Good idea, I'll make that change

2022-03-21 06:20 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
> +        result shouldBe okGroup
I think we don’t get `Not Authorized` error in `Groups` anymore since we are enabling everyone to view the group details in `MembershipValidations.scala`. Let's confirm with @remerle whether to keep this or to remove this.

2022-03-21 06:20 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipValidations.scala
> +      authPrincipal.isGroupMember(groupId) || authPrincipal.isSystemAdmin || canViewGroupDetails
Same as the other comment I gave. Since now we are enabling everyone to view `Group Details`, this (`authPrincipal.isGroupMember(groupId) || authPrincipal.isSystemAdmin || canViewGroupDetails`) will always be `true` and we won't get `NotAuthorizedError` here anymore until we change `canViewGroupDetails` to `false` (which we won't be doing since we want everyone to see the group details). Let’s confirm with Ryan whether to keep it as it is or make any changes.

2022-03-23 18:49 UTC, remerle requested changes
@nspadaccino minor change

2022-03-23 18:49 UTC, remerle commented on modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
> +        result shouldBe okGroup
@nspadaccino Yeah, let's go ahead and remove this test since we are not actually verifying that we will `return an error if not authorized`.

2022-04-04 20:17 UTC, remerle approved these changes
LGTM 👍

2022-04-11 20:18 UTC, merged