Updated wildcard filter for global recordset search with reverseFQDN
vinyldns/vinyldns pull request #1100
Opened 2022-03-22 14:25 UTC by Jay07GIT

### Changes in this pull request:
- Updated wildcard filter for global recordset search with `reverseFQDN` using `recordset_data` table

2022-04-04 20:32 UTC, remerle requested changes
See my comments.

Additionally, for any methods added or updated, please include a method-level comment. We should use the javadoc standard.  There's a lack of comments throughout the code, and we should look to incrementally improve that on every commit. You can read javadocs in the Scala style guide [here](https://docs.scala-lang.org/style/scaladoc.html#objects).

The comments should include:
- A description of what the method does
- Documentation for each parameter using `@param`
- Documentation for the return value using `@return`

2022-04-04 20:32 UTC, remerle commented on modules/mysql/src/main/resources/db/migration/V3.24__RecordSetData.sql
> +);
With flyway, you cannot modify existing, applied, schemas. If you want to change this table, it will have to be as a new flyway changeset.

Something like this:
```sql
ALTER TABLE recordset_data 
ADD COLUMN zone_name VARCHAR(256) AFTER zone_id;

ALTER TABLE recordset_data 
ADD COLUMN owner_group_id CHAR(36) AFTER ip;
```

This also leads me to wonder why we need to store the  zone and owner group information? We should be able to perform a `LEFT JOIN` on the `zone`

2022-04-04 20:32 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
> +         | WHERE zone_id = {zone_id} AND zone_name = {zone_name} AND type = {type}
Why do we need the `zone_name` if we have the `zone_id`?

2022-04-04 20:32 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
> +         | WHERE zone_id = {zone_id} AND zone_name = {zone_name}
Same as the previous comment. I'm not sure why the `zone_name` is necessary since the `zone_id` should uniquely identify the zone.

2022-04-04 20:32 UTC, remerle commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
> +         |WHERE owner_group_id = {ownerGroupId}
This could be done with a `JOIN`

2022-04-08 11:19 UTC, Jay07GIT commented on modules/mysql/src/main/resources/db/migration/V3.24__RecordSetData.sql
> +);
1. I thought of JOIN queries will cause a performance issue. So i Added `record_name` and `owner_id` columns in the `recordset_data` table.

2022-04-08 11:20 UTC, Jay07GIT commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
> +         | WHERE zone_id = {zone_id} AND zone_name = {zone_name} AND type = {type}
Sorry, Actually its `record_name`. I renamed  `zone_name` to `record_name`.

2022-04-08 11:20 UTC, Jay07GIT commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
> +         | WHERE zone_id = {zone_id} AND zone_name = {zone_name}
Actually its `record_name`. Just now i noticed the name. I renamed  `zone_name` to `record_name`.

2022-04-08 12:58 UTC, Jay07GIT commented on modules/portal/conf/routes
> +GET           /api/recordsets                    @controllers.VinylDNS.listRecordSetData
Removed `line number 27`

2022-04-11 20:36 UTC, remerle requested changes

2022-04-11 20:36 UTC, remerle commented on modules/mysql/src/main/resources/db/migration/V3.24__RecordSetData.sql
> +  FULLTEXT INDEX recordset_data_reverse_fqdn_fulltext_index(reverse_fqdn),
Why do we need a `FULLTEXT INDEX` on the `reverse_fqdn`? If we do need it, it has to be added to the v3.26 flyway change.

2022-04-13 14:56 UTC, Jay07GIT commented on modules/mysql/src/main/resources/db/migration/V3.24__RecordSetData.sql
> +  FULLTEXT INDEX recordset_data_reverse_fqdn_fulltext_index(reverse_fqdn),
Tried to implement <`match` `against`> in replacement of `like` in sql queries which will be improve performance of search with `fulltext index`. But i found that, it wont support for wildcard filters and characters used for search should be minimum 4 which will cause unnecessary confusion for the users. 

Hence i removed `full text` for `fqdn` and `reverse_fqdn`.

2022-04-13 16:18 UTC, Jay07GIT commented on modules/mysql/src/main/resources/db/migration/V3.24__RecordSetData.sql
> +  FULLTEXT INDEX recordset_data_reverse_fqdn_fulltext_index(reverse_fqdn),
I tried to replace `JOIN` with [`Match` `against`] for recordset search SQL queries which uses `fulltext index`. But i found that `fulltext index` will not work with wildcard filters and it requires 4 characters minimum to search the word. This will cause unwanted confusion with the USERS in `recordset search`.

Hence i removed` fulltext index` for `fdqn` and `reverse_fdqn`.

2022-04-14 14:03 UTC, remerle requested changes
Please revisit the method comments and try to be as descriptive as possible - I provided an example.

2022-04-18 06:29 UTC, Jay07GIT commented on modules/mysql/src/main/resources/db/migration/V3.24__RecordSetData.sql
> +  FULLTEXT INDEX recordset_data_record_data_fulltext_index(record_data)
Added alter query for drop full text indexes(fqdn, reverse_fqdn)

2022-04-18 06:30 UTC, Jay07GIT commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetDataRepository.scala
> +        */
Modified as suggested

2022-04-19 20:12 UTC, remerle requested changes
@Jay07GIT See my notes. Let's get the SQL DDL fixed up.

Of primary concern:
- The `record_data` column should have a `FULLTEXT INDEX`
- The `data` column `BLOB` should be removed from the `recordset_data` table
    - Use `JOIN` clauses where necessary
- Do not modify existing Flyway changesets
	- If you modify the existing changesets, then Flyway will not apply the changes which is no bueno

2022-04-19 20:12 UTC, remerle commented on modules/mysql/src/main/resources/db/migration/V3.26__RecordSetData_RecordName_OwnerGroup.sql
> +ALTER TABLE recordset_data DROP INDEX recordset_data_reverse_fqdn_fulltext_index;
We want to add a `FULLTEXT INDEX` on `record_data` here too.

```sql
CREATE FULLTEXT INDEX fulltext_record_data_index ON recordset_data_record_data (record_data);
```

2022-04-21 13:12 UTC, Jay07GIT commented on modules/mysql/src/main/resources/db/migration/V3.26__RecordSetData_RecordName_OwnerGroup.sql
> +CREATE SCHEMA IF NOT EXISTS ${dbName};
As suggested , I done the below modification

> Added `JOIN` for the `data BLOB` column and dropped from the `recordset_data` table.
> Removed the record_name and owner_id column from the `recordset_data` table. And used the same `JOIN` to get `record_name` and `owner_id` column from the `recordset` table.

2022-04-21 13:15 UTC, Jay07GIT commented on modules/mysql/src/main/resources/db/migration/V3.26__RecordSetData_RecordName_OwnerGroup.sql
> +ALTER TABLE recordset_data DROP INDEX recordset_data_reverse_fqdn_fulltext_index;
Since, we already have a `full text index` for `record_data` (with a typo), i dropped the full text index (`record_data`)and added a new one.

2022-05-13 17:39 UTC, remerle commented
Closing this out in favor of the updated PR #1125

2022-05-13 17:39 UTC, closed without merging