Reverse zones are updated as case insensitive
vinyldns/vinyldns pull request #1117
Opened 2022-04-28 11:36 UTC by Jay07GIT

Fixes #957.

Changes in this pull request:
- Reverse zone are updated with case insensitive.
- `PTR` records can be added in the `reverse_zone` irrespective of its upper and lower cases.

2022-04-29 16:08 UTC, nspadaccino commented on modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala
>    def convertPTRtoIPv4(zone: Zone, recordName: String): String = {
I think it would be good to have some additional unit tests in `vinyldns/api/domain/ReverseZoneHelpersSpec.scala` to test the case insensitivity of this method and `convertPTRtoIPv6`

2022-05-03 10:45 UTC, Aravindh-Raju submitted a review, later dismissed

2022-05-03 12:16 UTC, Jay07GIT commented on modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala
>    def convertPTRtoIPv4(zone: Zone, recordName: String): String = {
Added reverse zone unit test cases with uppercase as suggested.

2022-05-17 17:08 UTC, remerle requested changes

2022-05-17 17:08 UTC, remerle commented on modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala
> +    val zoneName = Pattern.compile("in-addr.arpa.", Pattern.CASE_INSENSITIVE).split(zone.name)(0)
This is not idiomatic Scala. We want to try to avoid pulling in Java libraries. To do this in Scala, you would use the `.r` function:

```scala
    val zoneName = "(?i)in-addr.arpa.".r.split(zone.name)(0)
```

However, this seems like overkill when we're just trying to remove the suffix. Instead, we can do this:
```suggestion
    val zoneName = zone.name.dropRight("in-addr.arpa.".length)
```

2022-05-19 09:10 UTC, Jay07GIT commented on modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala
> +    val zoneName = Pattern.compile("in-addr.arpa.", Pattern.CASE_INSENSITIVE).split(zone.name)(0)
Updated the code as suggested.

2022-05-19 09:10 UTC, Jay07GIT commented on modules/core/src/main/scala/vinyldns/core/domain/zone/Zone.scala
> +  val isIPv6: Boolean = name.endsWith("ip6.arpa.") || name.endsWith("IP6.ARPA.")
Updated the code as suggested.

2022-05-19 19:42 UTC, remerle approved these changes

2022-05-19 19:43 UTC, merged