Validate Group Fields in API
vinyldns/vinyldns pull request #1121
Opened 2022-05-02 09:12 UTC by Aravindh-Raju

Fixes issue #1120.

Changes in this pull request:
- Added validation similar to Portal in API to throw an error message when we try to create a group with `name` and/or `email` fields empty. Now we cannot create a group with empty `name` and/or `email` fields through API and we'll get the message `Group name and email cannot be empty.` when either or both is empty.

2022-05-02 16:48 UTC, nspadaccino submitted a review, later dismissed
Looks good

2022-05-04 05:19 UTC, Jay07GIT submitted a review, later dismissed
Looks good to me.

2022-05-25 14:52 UTC, remerle requested changes
Minor tweak

2022-05-25 14:52 UTC, remerle commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +      case Some(value) if value.name.isEmpty || value.email.isEmpty =>
It may be a good idea to `.trim` the values in case they're whitespace.

```suggestion
      case Some(value) if value.name.trim.isEmpty || value.email.trim.isEmpty =>
```

It's also a good idea to handle the possibility of a null value:
```suggestion
      case Some(value) if Option(value.name).forall(_.trim.isEmpty) || Option(value.email).forall(_.trim.isEmpty)=>
```

2022-05-26 05:43 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +      case Some(value) if value.name.isEmpty || value.email.isEmpty =>
Made the suggested changes.

2022-08-03 13:49 UTC, nspadaccino approved these changes

2022-09-12 20:46 UTC, merged