Add Unit Tests For Zone Search Case Insensitivity
vinyldns/vinyldns pull request #1152
Opened 2022-07-06 14:00 UTC by nspadaccino

Fixes #1143

2022-07-07 13:47 UTC, Jay07GIT requested changes

2022-07-07 13:47 UTC, Jay07GIT commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala
> +            zoneNameFilter.map(flt => s"LOWER ( z.name ) LIKE '${ensureTrailingDot(flt.replace('*', '%').toLowerCase())}'"),
We can ignore these changes, since **zone search** is already working with case sensitive. Other wise looks good. Good that we covered tests on **zone search** with case sensitive.

2022-07-08 04:52 UTC, Jay07GIT approved these changes
Looks good to me

2022-07-08 04:53 UTC, Jay07GIT approved these changes

2022-09-13 21:08 UTC, arpit4ever approved these changes
LGTM

2022-09-14 14:43 UTC, merged