Allow All Users to View Any Shared Zone
vinyldns/vinyldns pull request #1162
Opened 2022-08-05 13:58 UTC by nspadaccino

Fixes #643

All users are able to make changes within shared zones, so it makes sense that they should be able to view the shared zones as well. This change allows all users to view a shared zone regardless of membership

2022-08-10 07:52 UTC, Aravindh-Raju reviewed
Everything looks fine and I'm able to view shared zones. I just have few doubts. 

Non-owners are supposed to have `Read-only` access right? But I am able to make changes (add, delete and update records) from the zone view itself. And also, it doesn't require admin group to make changes like in DNS Changes page which must be a required field. I've attached a pic for your reference.

<img width="1904" alt="Screenshot 2022-08-10 at 1 09 06 PM" src="https://user-images.githubusercontent.com/61419792/183845314-cf8d26a7-3a20-4336-b985-2fc61d76d398.png">

We only want all the users to view shared zones but continue making changes from DNS Changes right?

2022-08-22 06:45 UTC, Aravindh-Raju requested changes

2022-08-22 06:45 UTC, Aravindh-Raju commented on modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
> +            <button id="create-record-button" class="btn btn-default" ng-if="canReadZone" ng-click="createRecord(defaultTtl)"><span class="fa fa-plus"></span> Create Record Set</button>
Just a minor change. The other conditions from `canCreateRecords` except the condition `$scope.zoneInfo.shared` must be added to the `ng-if` because I'm able to see the `Create Record Set` button and create records when I'm given `read-only` access via ACL which shouldn’t be the expected behavior. When given read-only access, I shouldn’t be able to see the button and shouldn’t be able to create a record. The reason is, the condition `canCreateRecordsViaAcl()` was not present in `ng-if`. Changing the `ng-if` as follows solves the problem:
```
<button id="create-record-button" class="btn btn-default" ng-if="canReadZone && (zoneInfo.accessLevel == 'Delete' || canCreateRecordsViaAcl())" ng-click="createRecord(defaultTtl)"><span class="fa fa-plus"></span> Create Record Set</button>
```
We just need to add those 2 conditions to `ng-if`.
Also, we can remove the commented line.

2022-08-22 06:45 UTC, Aravindh-Raju commented on modules/portal/public/lib/controllers/controller.records.js
> +//        $scope.canCreateRecords = $scope.zoneInfo.accessLevel == 'Delete' || canCreateRecordsViaAcl();
We can remove this commented line.

2022-08-24 09:11 UTC, Aravindh-Raju approved these changes

2022-08-30 07:09 UTC, Jay07GIT approved these changes
LGTM

2022-11-08 20:03 UTC, arpit4ever approved these changes
LGTM

2022-11-08 20:15 UTC, merged