Added API and Updated Portal for deleted zones history
vinyldns/vinyldns pull request #1169
Opened 2022-08-26 13:26 UTC by Jay07GIT

Fixes #.

Changes in this pull request:
- Added API for deleted zones history (`zones/deleted/changes`)
- Made Portal changes to view deleted zones history

2022-09-06 05:55 UTC, Aravindh-Raju reviewed
Everything works fine as expected locally. Is it possible to increase code coverage further? I see few warnings by `codecov` in the lines that were added as not covered by tests. I'm seeing that in `Files Changed` column at the files `MySqlZoneChangeRepository.scala`, `ZoneProtocol.scala` and `ZoneService.scala`. Code coverage will be increased well enough if we are able to cover those lines in tests.

2022-09-06 05:55 UTC, Aravindh-Raju commented on modules/mysql/src/main/resources/db/migration/V3.28__AlterZoneAccess.sql
> +ADD zone_status CHAR(36) NOT NULL
Since we are adding a new column `zone_status`, I think we'll need to populate this column for existing data in our production database (other envs too), possibly using the `rsdump` utility which we used in the [BLOB issue](https://github.com/vinyldns/vinyldns/issues/975) for the same populating purpose.

2022-09-06 05:55 UTC, Aravindh-Raju commented on modules/portal/public/lib/controllers/controller.zones.js
> +        $log.log("Displaying my Deleted zones: ", $scope.deletedZones);
I'm thinking if we need to have `log` statements which will be displayed in production too. It may not be a great idea to expose `log` messages in our production code. Ideally, we should remove such log messages with a build script before deployment. I think we can have a separate PR to handle all the `logs` in `portal` module after further discussion.

2022-09-06 06:11 UTC, Jay07GIT commented on modules/mysql/src/main/resources/db/migration/V3.28__AlterZoneAccess.sql
> +ADD zone_status CHAR(36) NOT NULL
Yes. Thats right. We need to populate the data for existing record by using separate utility. We will try to do this by `rsdump`. Noted.

2022-09-06 06:15 UTC, Jay07GIT commented on modules/portal/public/lib/controllers/controller.zones.js
> +        $log.log("Displaying my Deleted zones: ", $scope.deletedZones);
Sure. Will discuss about it.

2022-09-09 12:19 UTC, Jay07GIT commented on modules/portal/public/lib/controllers/controller.zones.js
> +        $log.log("Displaying my Deleted zones: ", $scope.deletedZones);
Portal logs updated to debug.

2023-06-22 06:02 UTC, Aravindh-Raju requested changes
Functionality looks good. Just need a few changes.

2023-06-26 11:45 UTC, Jay07GIT commented on modules/portal/public/lib/controllers/controller.zones.js
> +                    .getDeletedZones(zonesPaging.maxItems, undefined, $scope.query)
updated the code.

2023-07-06 05:07 UTC, Aravindh-Raju approved these changes
Tested it out locally. LGTM!

2023-07-06 19:26 UTC, JoshSEdwards commented
Tested it locally and it looked good to me. Only one weird thing I noticed (which may be desirable?) is that you can connect and abandon the same zone over and over again, and it appears multiple times in the My Abandoned Zones tab. Each time the zone is newly connected it gets a new UUID. Not sure if that's by design.

2023-07-06 19:27 UTC, JoshSEdwards approved these changes

2023-07-07 13:40 UTC, nspadaccino reviewed
One potential issue I noticed is that if I abandon a zone with a specific admin group, and then delete that group, the abandon history for that zone gets removed, and does not come back if I create the group again. I'm assuming that happens because the zone deletes are tied to a group ID, and deleting and adding a group with the same name changes the ID. So I'm not sure if that behavior could be changed.

2023-09-02 08:34 UTC, Jay07GIT commented
SInce faced conflicts and git sign issue. This PR has been replicated to [New PR](https://github.com/vinyldns/vinyldns/pull/1284)

2023-09-02 08:35 UTC, closed without merging