Allow Super Users to Update Record Owner Group in Shared Zone
vinyldns/vinyldns pull request #1174
Opened 2022-09-02 18:34 UTC by nspadaccino

Fixes #644

Changes in this pull request:
Super users can now update a record's owner group in a shared zone if the owner group is the only attribute being changed. This prevents super users from having to add themselves to a group temporarily to make that update.

2022-09-05 04:53 UTC, Jay07GIT requested changes
I could see many `//todo` in code. If the required changes has been made already, Can you please remove it.

2022-09-05 06:30 UTC, Jay07GIT requested changes
I could see empty in `Record Owner Group` dropdown field for `unowned Owner Group Name`. Can you add `if (owner group is empty) = unowned` for shared zone in Portal(html).

<img width="607" alt="image" src="https://user-images.githubusercontent.com/88772914/188376292-afe88281-dfef-4612-9dd5-903eb54814c0.png">

2022-09-06 20:32 UTC, nspadaccino commented on modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
> + //todo
Jay, for your above comment do you mean that we should put a placeholder for the dropdown instead of having it show up empty initially? I handled that in my previous PR: https://github.com/vinyldns/vinyldns/pull/1162/files#diff-8188ea534e96b6840c551ca6795b5f5b1ee4379aff0000630536ac6ea9942e13R458

2022-09-08 09:36 UTC, Jay07GIT commented on modules/api/src/it/scala/vinyldns/api/domain/record/RecordSetServiceIntegrationSpec.scala
> + //todo
Yes. Merge both PR will resolve the issue. Looks good.

2022-09-08 09:38 UTC, Jay07GIT submitted a review, later dismissed
Looks good to me.

2022-09-09 09:01 UTC, Aravindh-Raju approved these changes
Checked the working locally, LGTM!

2023-02-20 21:18 UTC, closed without merging