Make the Number of Groups Displayed in a List a Configurable Value
vinyldns/vinyldns pull request #1205
Opened 2022-11-17 22:15 UTC by nspadaccino

Fixes #1200

Added membership-routing-max-groups-list-limit config value to the portal config. The value is now used in the frontend to manage how many groups to display in the owner group dropdown lists.

2023-01-19 10:35 UTC, Aravindh-Raju requested changes

2023-01-19 10:35 UTC, Aravindh-Raju commented on modules/portal/app/models/Meta.scala
> +      config.getOptional[Int]("api.limits.membership-routing-max-groups-list-limit").getOrElse(2500)
Just for my clarification, why are we setting the value as `2500` instead of the default `3000` mentioned in the config (similar to that of `batch-change-limit`)?

2023-01-19 10:35 UTC, Aravindh-Raju commented on modules/portal/public/lib/controllers/controller.groups.js
> +    $scope.maxGroupItemsDisplay = 2000;
Should we set the default value of 3000 defined in the config here too, to make it uniform everywhere?

2023-07-05 21:19 UTC, JoshSEdwards approved these changes
LGTM

2023-07-26 05:41 UTC, Jay07GIT approved these changes
LGTM

2023-08-09 10:41 UTC, Aravindh-Raju approved these changes
LGTM!

2023-08-09 18:35 UTC, arpit4ever approved these changes
LGTM

2023-08-09 18:56 UTC, merged