group email validation code along with unit test
vinyldns/vinyldns pull request #1215
Opened 2023-01-05 07:08 UTC by ssranjani06

Fixes #1213 

Changes in this pull request:
-We have added emailvalidation  for groups in the api side

2023-01-18 12:54 UTC, Aravindh-Raju requested changes
Add the config details in [config-api.md](https://github.com/vinyldns/vinyldns/blob/master/modules/docs/src/main/mdoc/operator/config-api.md) file too.

2023-01-19 09:37 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
> +      }
Can you add a similar unit test to verify wildcard email domain (eg: `*dummy.com`)?

You can change the following line in this file to include the wildcard email domain:
```
 private val mockValidEmailConfig = ValidEmailConfig(valid_domains = List("test.com", "*dummy.com"))
 ```

2023-01-20 09:41 UTC, Aravindh-Raju approved these changes

2023-02-22 09:34 UTC, Jay07GIT requested changes

2023-02-27 05:34 UTC, Jay07GIT requested changes

2023-02-27 05:34 UTC, Jay07GIT commented on modules/api/src/test/functional/tests/membership/create_group_test.py
> -            "name": f"test-create-group-success{shared_zone_test_context.partition_id}",
I am curious to know, why this string interpolation was removed?.

2023-02-27 05:34 UTC, Jay07GIT commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +        ("^[A-Za-z0-9._%+-]+@" + emailDomains.mkString(",").replaceAllLiterally("*", "[A-Za-z0-9.]*").replaceAllLiterally(",", "|") + "$").r
Hope this condition is checking the wildcard in entire domain string. If yes, this should validate the string starts with wildcard, not with the entire string.

2023-02-27 05:34 UTC, Jay07GIT commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +      if (emailDomains.mkString(",").contains("*")) {
wild card can be * and %. Kindly add condition for both.

2023-02-27 18:01 UTC, arpit4ever requested changes

2023-03-03 21:51 UTC, nspadaccino requested changes
I found some edge cases we are not currently handling:

```
test@.test.com
test@..test.com
test@.@.test.com
test@.@@.test.com
test@....@@@.test.com
```

For the above, it looks like characters between the local and domain parts aren't being checked properly.

`test@test.com.test.com`

It looks like you can chain domain parts together with dots.

```
.test@test.com
te.....st@test.com
```

It is currently allowing dots at the beginning of the local part, and also consecutive dots.

```
te@st@test.com
@te@st@test.com
```

We are currently allowing @ symbols in the local part. There should only be one @ symbol allowed.

`tes"(),:;<>@[\]t@test.com`

These special characters should not be allowed. According to RFC 5322, the only special characters that should be allowed are 

> !#$%&'*+-/=?^_`{|}~

This Wikipedia article details the RFC email address requirements with a bunch of examples: 
https://en.wikipedia.org/wiki/Email_address#Syntax

I also found a useful article detailing a variety of different regexes for different levels of email validation: 
https://www.baeldung.com/java-email-validation-regex

2023-03-08 15:11 UTC, nspadaccino commented
New regex looks good, but can you add some unit tests for some of the examples I gave in my previous comment?

2023-03-09 08:12 UTC, Aravindh-Raju requested changes

2023-03-09 08:12 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
> +      }
We can have new line after each test here too following the existing file format

2023-03-09 08:12 UTC, Aravindh-Raju commented on modules/api/src/test/scala/vinyldns/api/domain/membership/MembershipServiceSpec.scala
> +
Can remove this added new lines.

2023-03-09 08:12 UTC, Aravindh-Raju commented on modules/core/src/main/scala/vinyldns/core/Messages.scala
> +  val invalidEmailValidationErrorMsg = "Please enter a valid Email ID."
As mentioned already, we can capitalise the first letters here.

2023-03-09 09:14 UTC, ssranjani06 commented
> New regex looks good, but can you add some unit tests for some of the examples I gave in my previous comment?



> New regex looks good, but can you add some unit tests for some of the examples I gave in my previous comment?



> New regex looks good, but can you add some unit tests for some of the examples I gave in my previous comment?



> 
I added unit tests as mentioned. I also made a change in the regex where the email will not start with dot and end with dot.
It will not allow two consecutive dots.

2023-03-14 06:41 UTC, ssranjani06 commented on modules/api/src/test/functional/tests/membership/create_group_test.py
added

2023-03-15 17:08 UTC, arpit4ever approved these changes
LGTM
Verified locally.

2023-03-15 19:08 UTC, nspadaccino approved these changes

2023-03-15 19:09 UTC, merged