Display total record count in Manage Records tab in Zone view #1244
vinyldns/vinyldns pull request #1247
Opened 2023-04-13 06:29 UTC by ssranjani06

Fixes #.

Changes in this pull request:
Total Number of records Will be displayed in the Manage Records Tab.

2023-04-24 04:21 UTC, Aravindh-Raju requested changes

2023-04-24 04:21 UTC, Aravindh-Raju commented on modules/portal/public/lib/controllers/controller.records.js
> +                 $log.log('RecordService::getTotalRecordCount-success',  response.data);
Can you change this to `$log.debug` or remove this if it's not necessary, so that it won't show up in browser console.

2023-04-24 04:21 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala
> +          complete(StatusCodes.OK, count)
Seems like this is not covered by test. Can you add some tests in `RecordSetRoutingSpec.scala` similar to the existing tests we have, so that we can increase test coverage.

2023-06-27 12:44 UTC, Aravindh-Raju requested changes

2023-06-27 12:44 UTC, Aravindh-Raju commented on scriptFile.scala
The file `scriptFile.scala` seems to be added by mistake. Please delete it.

2023-06-28 03:31 UTC, ssranjani06 commented on scriptFile.scala
Deleted the file

2023-07-06 20:01 UTC, JoshSEdwards commented
Tested locally and it looks like it's working fine. I'm not sure I like the additional string saying "Total Number of Records: X". Might be cleaner just to add the count to the already existing string, so it's like "Records: X"

2023-07-07 13:48 UTC, nspadaccino commented
> Tested locally and it looks like it's working fine. I'm not sure I like the additional string saying "Total Number of Records: X". Might be cleaner just to add the count to the already existing string, so it's like "Records: X"

I also think that would be a good idea.

2023-07-13 20:00 UTC, JoshSEdwards commented on modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
> +        <h3 class="panel-title">Records {{ getRecordPageTitle() }} <br/><br/>Records:{{showRecordCount}}</h3>
I think it would be preferable to get rid of the second line and just have the record count displayed after the panel title, like this:

`<h3 class="panel-title">Records: {{showRecordCount}} {{ getRecordPageTitle() }} </h3>`

Also, (and I know this is unrelated to your change) I don't think I've ever seen anything after "Records" -- what is getRecordPageTitle() meant to show?

2023-07-26 05:16 UTC, Jay07GIT commented on modules/api/src/test/functional/tests/recordsets/get_recordset_test.py
> +def test_get_recordsetcount(shared_zone_test_context):
This function not testing the record set count. Looks like its testing the status code 200. Can you please add `assert_that` for verify pass and fail.

2023-07-26 05:18 UTC, Jay07GIT commented on modules/api/src/test/functional/tests/recordsets/get_recordset_test.py
> +    client.get_recordset_count(shared_zone_test_context.ok_zone["id"],status=200)
Here we given name as `recordset_count` but for test we used `test_get_recordsetcount` . Can you please change it to `test_get_recordset_count`

2023-07-26 05:21 UTC, Jay07GIT commented on modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
> +    "return Total RecordCount" in {
Can you name it as RecordSetCount? 

I guess we can name the test case as `return a total RecordSetCount in the specified zone` something like this

2023-07-26 05:23 UTC, Jay07GIT commented on modules/api/src/test/scala/vinyldns/api/domain/record/RecordSetServiceSpec.scala
>      "return a NotAuthorizedError if the user is not authorized to access the zone" in {
Can you add a test for not authorised user?

2023-07-26 05:24 UTC, Jay07GIT commented on modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
> +  private val RecordCount = RecordSetCount(5)
Variable name should start with small. Its a `recordSetCount`

2023-07-26 05:25 UTC, Jay07GIT commented on modules/api/src/test/scala/vinyldns/api/route/RecordSetRoutingSpec.scala
> +        case notAuthorizedZone.id => Left(NotAuthorizedError("no way"))
Just for my understanding . Is it notAuthorizedUser or notAuthorizedZone?

2023-07-26 05:29 UTC, Jay07GIT commented on modules/portal/public/lib/controllers/controller.records.js
> +    $scope.showRecordCount = 0;
Same again . `showRecordSetCount` . Just a curious to know . Why we named it as showRecordCount? I guess it's storing the value of recordSetCount. We can name similar.

2023-07-26 05:34 UTC, Jay07GIT commented on modules/portal/test/controllers/VinylDNSSpec.scala
> +    ".getRecordSetCount" should {
I couldn't find the positive test to get the record set count. Can you please add. If exists please ignore.

2023-07-26 05:35 UTC, Jay07GIT commented on modules/portal/public/lib/services/records/service.records.js
> +       this.recordSetCount = function (zid) {
Can you please add tests?

2023-07-26 05:36 UTC, Jay07GIT commented on modules/portal/public/lib/controllers/controller.records.js
> + $scope.showLengthRecords=function getTotalRecordCount() {
Can you please add tests?

2023-08-16 05:19 UTC, ssranjani06 commented on modules/portal/app/views/zones/zoneTabs/manageRecords.scala.html
> +        <h3 class="panel-title">Records {{ getRecordPageTitle() }} <br/><br/>Records:{{showRecordCount}}</h3>
Resolved

2023-08-16 07:14 UTC, ssranjani06 commented on modules/portal/public/lib/controllers/controller.records.js
> +    $scope.showRecordCount = 0;
Changed it to showRecordSetCount

2023-09-25 15:41 UTC, arpit4ever commented
New PR https://github.com/vinyldns/vinyldns/pull/1304
Closing this PR.

2023-09-25 15:41 UTC, closed without merging