Add an Option to Filter Out PTR Zones in the Zones View
vinyldns/vinyldns pull request #1272
Opened 2023-06-23 21:02 UTC by nspadaccino

Fixes https://github.com/vinyldns/vinyldns/issues/1122

A checkbox option to filter out PTR zones has been added in the zones view. This filter will still apply when searching for zone names

2023-06-27 06:27 UTC, Aravindh-Raju requested changes

2023-06-27 06:27 UTC, Aravindh-Raju commented on modules/portal/app/views/zones/zones.scala.html
> +<!--                                    </div>-->
We can remove this.

2023-06-27 08:44 UTC, Aravindh-Raju requested changes
When both `Hide PTR Zones` and `Search by admin group` checkboxes are checked, the PTR Zones still shows up.

2023-07-05 21:05 UTC, closed without merging

2023-07-05 21:06 UTC, nspadaccino commented
Raised request on wrong repo

2023-07-05 21:07 UTC, arpit4ever commented
New PR https://github.com/vinyldns/vinyldns/pull/1274