list abandoned zones
vinyldns/vinyldns pull request #1284
Opened 2023-07-24 12:55 UTC by Jay07GIT

Fixes #617

Changes in this pull request:

- Added API for deleted zones history (zones/deleted/changes)
- Made Portal changes to view deleted zones history.
- Removed Cascade from zone_access table. We use this on comparing zone_change table .
- Added zone_status column in zone_access table to identify the deleted zones and used the same in deleting the group.

2023-08-02 07:22 UTC, Aravindh-Raju requested changes

2023-08-02 07:22 UTC, Aravindh-Raju commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
> +              deletedZoneResults.filter(r => r.zone.name.contains(zoneNameFilter.getOrElse("not found")))
I see zoneNameFilter and pagination are not covered by tests. We can add those tests in `MySqlZoneChangeRepositoryIntegrationSpec.scala` and increase the code coverage.

2023-08-02 07:22 UTC, Aravindh-Raju commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
> +          val deletedZonesWithStartFrom: List[ZoneChange] = startFrom match {
Seems like pagination is not working as expected. Maybe a problem with how `startfrom` is used here. I have attached screenshots for reference. There were 4 items before pagination. But while paginating, I get the same results in every page. Needs to be fixed.

<img width="1904" alt="Screenshot 2023-08-02 at 12 34 36 PM" src="https://github.com/vinyldns/vinyldns/assets/61419792/1787a922-c844-4f3a-9a28-69eec750929e">
<img width="1904" alt="Screenshot 2023-08-02 at 12 37 41 PM" src="https://github.com/vinyldns/vinyldns/assets/61419792/6312a3f4-16ed-4f02-b8fb-688c36c3abaf">
<img width="1904" alt="Screenshot 2023-08-02 at 12 37 46 PM" src="https://github.com/vinyldns/vinyldns/assets/61419792/f104dbd2-a421-4cc1-873b-7931d9cde233">

2023-08-04 12:57 UTC, Jay07GIT commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
> +          val deletedZonesWithStartFrom: List[ZoneChange] = startFrom match {
Startfrom changed from zone name to zone id. Now its working fine.

2023-08-15 15:39 UTC, arpit4ever approved these changes
LGTM
Tested (GUI & API) functionality locally.

2023-08-16 15:20 UTC, nspadaccino requested changes
I'm seeing a bug in the zones view.
If I log in as one user, create a group, and connect a zone, then log in with another user not in that group, I am able to see the zone in My Zones, and I am able to click on it. When I click on it, I get a 403 error (since that user doesn't have permission to view that private zone).
<img width="1727" alt="Screenshot 2023-08-16 at 11 19 09 AM" src="https://github.com/vinyldns/vinyldns/assets/37352107/bd31d5fa-2fc1-48e4-8587-4c549e41a0df">
Other groups' private zones shouldn't appear in My Zones tab

2023-08-16 15:33 UTC, nspadaccino commented
Also, it seems like wildcard search isn't working correctly for abandoned zones.
In My Zones, I can search for "o*" and see the zone "ok". But when I search for "o*" in abandoned zones, I get no results.
<img width="1727" alt="Screenshot 2023-08-16 at 11 30 24 AM" src="https://github.com/vinyldns/vinyldns/assets/37352107/955a48e6-0c35-4bd1-9a4e-8b2c243bbb82">
<img width="1727" alt="Screenshot 2023-08-16 at 11 30 32 AM" src="https://github.com/vinyldns/vinyldns/assets/37352107/c9f107e1-fdb5-4c90-a591-c36cd362a3cb">
<img width="1727" alt="Screenshot 2023-08-16 at 11 30 40 AM" src="https://github.com/vinyldns/vinyldns/assets/37352107/4a6a809a-ea6f-4b96-8873-0e73de0e148c">
<img width="1727" alt="Screenshot 2023-08-16 at 11 30 47 AM" src="https://github.com/vinyldns/vinyldns/assets/37352107/843f869c-59be-43e8-9181-78b1a9e3d6de">

2023-08-22 18:33 UTC, Jay07GIT commented
> Also, it seems like wildcard search isn't working correctly for abandoned zones. In My Zones, I can search for "o*" and see the zone "ok". But when I search for "o*" in abandoned zones, I get no results. <img alt="Screenshot 2023-08-16 at 11 30 24 AM" width="1727" src="https://user-images.githubusercontent.com/37352107/261059126-955a48e6-0c35-4bd1-9a4e-8b2c243bbb82.png"> <img alt="Screenshot 2023-08-16 at 11 30 32 AM" width="1727" src="https://user-images.githubusercontent.com/37352107/261059156-c9f107e1-fdb5-4c90-a591-c36cd362a3cb.png"> <img alt="Screenshot 2023-08-16 at 11 30 40 AM" width="1727" src="https://user-images.githubusercontent.com/37352107/261059181-4a6a809a-ea6f-4b96-8873-0e73de0e148c.png"> <img alt="Screenshot 2023-08-16 at 11 30 47 AM" width="1727" src="https://user-images.githubusercontent.com/37352107/261059198-843f869c-59be-43e8-9181-78b1a9e3d6de.png">

Yes. its right . Since we used scala filter we dont need wildcard for seach. we can jus give "o" to search ok. zones.

2023-08-22 18:34 UTC, Jay07GIT commented
> I'm seeing a bug in the zones view. If I log in as one user, create a group, and connect a zone, then log in with another user not in that group, I am able to see the zone in My Zones, and I am able to click on it. When I click on it, I get a 403 error (since that user doesn't have permission to view that private zone). <img alt="Screenshot 2023-08-16 at 11 19 09 AM" width="1727" src="https://user-images.githubusercontent.com/37352107/261055201-bd31d5fa-2fc1-48e4-8587-4c549e41a0df.png"> Other groups' private zones shouldn't appear in My Zones tab

Oh yes. Updated the code. Now its working fine.

2023-09-12 17:58 UTC, arpit4ever approved these changes
LGTM

2023-09-12 18:16 UTC, nspadaccino approved these changes
looks good

2023-09-12 18:20 UTC, merged