Added api for record set count and displayed in portal
vinyldns/vinyldns pull request #1304
Opened 2023-09-25 07:09 UTC by Jay07GIT

Fixes #.

Changes in this pull request:
- Added api for record set count and displayed in portal

Steps: 
Login to the vinyldns 
zones > manage records

2023-09-25 15:40 UTC, arpit4ever commented on modules/portal/public/lib/controllers/controller.records.spec.js
> +            {algorithm: '2', type: '', fideleteSshfpngerprint: ''}];
possible typo.

2023-09-26 05:05 UTC, Jay07GIT commented on modules/portal/public/lib/controllers/controller.records.spec.js
> +            {algorithm: '2', type: '', fideleteSshfpngerprint: ''}];
Oops. Happened by mistake. Updated the code.

2023-09-27 05:59 UTC, Aravindh-Raju requested changes
Looks good to me except for a minor change.

2023-09-27 05:59 UTC, Aravindh-Raju commented on modules/api/src/test/functional/tests/recordsets/get_recordset_test.py
>  @pytest.mark.serial
Just a doubt, why do we have `@pytest.mark.serial` here and not on the other tests? Maybe it has been misplaced while recreating the PR. If so, we can remove that.

2023-09-27 09:13 UTC, Jay07GIT commented
> Looks good, but I'm wondering if we should also include documentation for the new api as part of this PR so we don't forget about it

Can we add a separate PR for Docs since we can have only api and portal changes here. I will open a PR and add it in comments.

2023-09-27 15:33 UTC, arpit4ever commented
> Looks good, but I'm wondering if we should also include documentation for the new api as part of this PR so we don't forget about it
Logged Issue
https://github.com/vinyldns/vinyldns/issues/1309

2023-09-28 11:00 UTC, Aravindh-Raju commented on modules/api/src/test/functional/tests/recordsets/get_recordset_test.py
>  @pytest.mark.serial
Jay mentioned `@pytest.mark.serial` is added to avoid conflict while creating new records. We can proceed with the merge if everything is alright.

2023-09-28 13:24 UTC, arpit4ever commented on modules/api/src/test/functional/tests/recordsets/get_recordset_test.py
>  @pytest.mark.serial
Sounds good.

2023-09-28 13:24 UTC, arpit4ever approved these changes
LGTM

2023-09-28 15:33 UTC, nspadaccino approved these changes

2023-09-28 19:55 UTC, merged