updated docs with Abandoned zones details
vinyldns/vinyldns pull request #1307
Opened 2023-09-26 09:55 UTC by Jay07GIT

Fixes #.

Changes in this pull request:
- Updated docs with Abandoned zones details.

2023-09-26 19:35 UTC, nspadaccino commented on modules/docs/src/main/mdoc/api/list-deleted-zones.md
> +title: "List / Abandoned Zones"
Should there be a slash here?

2023-09-26 19:35 UTC, nspadaccino commented on modules/docs/src/main/mdoc/api/list-deleted-zones.md
> +# List / Search Abandoned Zone
I think this should be List / Search Abandoned Zones, not Zone, as the singular makes it seem like you are searching within one zone

2023-09-27 05:52 UTC, Aravindh-Raju requested changes
Minor Changes. Looks good otherwise!

2023-09-27 05:52 UTC, Aravindh-Raju commented on modules/docs/src/main/mdoc/api/list-deleted-zones.md
> +startFrom     | *any*         | no          | In order to advance through pages of results, the startFrom is set to the `nextId` that is returned on the previous response.  It is up to the client to
The type of `startFrom` is `string` and not `any`. Type reference: https://github.com/vinyldns/vinyldns/blob/master/modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala#L118

2023-09-27 05:52 UTC, Aravindh-Raju commented on modules/docs/src/main/mdoc/portal/zones.md
> +[![Zones page - Abandoned All Zones](../img/portal/zones-all-deleted-zones.png){:.screenshot}](../img/portal/zones-all-deleted-zones.png)
Maybe we could change `Abandoned My Zones` to `My Abandoned Zones` and `Abandoned All Zones` to `All Abandoned Zones` so that it matches the previous two.

2023-09-27 09:34 UTC, Jay07GIT commented on modules/docs/src/main/mdoc/portal/zones.md
> +[![Zones page - Abandoned All Zones](../img/portal/zones-all-deleted-zones.png){:.screenshot}](../img/portal/zones-all-deleted-zones.png)
Updated the file.

2023-09-27 09:34 UTC, Jay07GIT commented on modules/docs/src/main/mdoc/api/list-deleted-zones.md
> +startFrom     | *any*         | no          | In order to advance through pages of results, the startFrom is set to the `nextId` that is returned on the previous response.  It is up to the client to
Good finding. Updated the file.

2023-09-27 09:34 UTC, Jay07GIT commented on modules/docs/src/main/mdoc/api/list-deleted-zones.md
> +# List / Search Abandoned Zone
Updated the file.

2023-09-27 09:34 UTC, Jay07GIT commented on modules/docs/src/main/mdoc/api/list-deleted-zones.md
> +title: "List / Abandoned Zones"
Updated the file.

2023-09-28 10:58 UTC, Aravindh-Raju approved these changes

2023-09-28 15:30 UTC, nspadaccino approved these changes
Looks good

2023-09-29 07:04 UTC, Aravindh-Raju requested changes
Just noticed `list-deleted-zones.md` should be added to the menu [here](https://github.com/vinyldns/vinyldns/blob/master/modules/docs/src/main/resources/microsite/data/menu.yml#L106), else we won't be able to view it in the doc website. 

```
      - title: Abandoned zones
        url: api/list-deleted-zones.html
        menu_section: zoneapireference
```

2023-10-05 17:04 UTC, Jay07GIT commented
> Just noticed `list-deleted-zones.md` should be added to the menu [here](https://github.com/vinyldns/vinyldns/blob/master/modules/docs/src/main/resources/microsite/data/menu.yml#L106), else we won't be able to view it in the doc website.
> 
> ```
>       - title: Abandoned zones
>         url: api/list-deleted-zones.html
>         menu_section: zoneapireference
> ```

Updated the file

2023-10-06 16:41 UTC, nspadaccino approved these changes

2023-10-06 17:13 UTC, arpit4ever approved these changes
LGTM

2023-10-06 17:14 UTC, merged