Update api docs
vinyldns/vinyldns pull request #1312
Opened 2023-10-04 09:34 UTC by Aravindh-Raju

Fixes #1310.

Changes in this pull request:
- Added new api routes and updated outdated details.

2024-02-21 05:23 UTC, Jay07GIT approved these changes
Looks good to me

2024-02-21 05:23 UTC, Jay07GIT commented on modules/docs/src/main/mdoc/api/get-recordset-count.md
> +200           | **OK** - The total record set count in a zone  is returned |
Please remove empty space next to zone.

2024-02-21 06:01 UTC, Aravindh-Raju commented on modules/docs/src/main/mdoc/api/get-recordset-count.md
> +200           | **OK** - The total record set count in a zone  is returned |
Fixed.

2024-02-21 14:29 UTC, nspadaccino commented on modules/docs/src/main/mdoc/api/list-recordset-changes.md
> +startFrom     | int           | no          | In order to advance through pages of results, the startFrom is set to the `nextId` that is returned on the previous response.  It is up to the client to
why is this type an int, while the startFrom type for List / Search RecordSets by Zone (and most other APIs) is a string?

2024-02-21 14:47 UTC, nspadaccino commented on modules/docs/src/main/mdoc/api/get-recordset-count.md
> +Gets the count of total recordsets in a specified zone
Missing period

2024-02-21 14:49 UTC, nspadaccino commented on modules/docs/src/main/mdoc/api/get-valid-email-domains.md
> +# Get Group
change to Get Valid Email Domains

2024-02-21 14:53 UTC, nspadaccino commented on modules/docs/src/main/mdoc/api/list-group-activity.md
> +userName            | string        | Username of user who made the change |
userName and groupChangeMessage are not present in the example response

2024-02-21 14:55 UTC, nspadaccino commented on modules/docs/src/main/mdoc/api/list-zone-changes-failures.md
> +# List Zone Changes
change to List Zone Change Failures

2024-02-21 14:57 UTC, nspadaccino commented on modules/docs/src/main/mdoc/api/list-zone-changes-failures.md
> +failedZoneChanges   | array of failed zone changes | array of zone changes sorted by created time in descending order |
Maybe we should add a section for the attributes of an individual failed zone change, like in the list-group-activity.md documentation?

2024-02-21 14:59 UTC, nspadaccino commented on modules/docs/src/main/mdoc/api/list-recordset-changes-failures.md
> +# List RecordSet Changes
change to List Recordset Change Failures

2024-02-21 15:00 UTC, nspadaccino requested changes
Few comments

2024-02-22 07:07 UTC, Aravindh-Raju commented on modules/docs/src/main/mdoc/api/list-recordset-changes.md
> +startFrom     | int           | no          | In order to advance through pages of results, the startFrom is set to the `nextId` that is returned on the previous response.  It is up to the client to
Here we use OFFSET in the query which requires an `int`. Whereas in other API's we use zone name or a certain column value as startFrom. For eg: [list zones](https://github.com/vinyldns/vinyldns/blob/master/modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneRepository.scala#L369)
We also use `int` in list zone changes and get batch changes api. Maybe because we can't have a unique string like in those other api's for these. Also, it's easier to use an OFFSET with `int` than using a column value as `string` and using a separate function to get the nextId and everything like we have for [list recordset](https://github.com/vinyldns/vinyldns/blob/master/modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala#L443).

2024-02-22 09:08 UTC, Aravindh-Raju commented on modules/docs/src/main/mdoc/api/get-recordset-count.md
> +Gets the count of total recordsets in a specified zone
Added.

2024-02-22 09:08 UTC, Aravindh-Raju commented on modules/docs/src/main/mdoc/api/get-valid-email-domains.md
> +# Get Group
Done

2024-02-22 09:08 UTC, Aravindh-Raju commented on modules/docs/src/main/mdoc/api/list-group-activity.md
> +userName            | string        | Username of user who made the change |
Added them in the response.

2024-02-22 09:09 UTC, Aravindh-Raju commented on modules/docs/src/main/mdoc/api/list-zone-changes-failures.md
> +failedZoneChanges   | array of failed zone changes | array of zone changes sorted by created time in descending order |
Added a separate section below.

2024-02-22 09:09 UTC, Aravindh-Raju commented on modules/docs/src/main/mdoc/api/list-recordset-changes-failures.md
> +#### EXAMPLE RESPONSE
Abridged the response.

2024-02-23 19:50 UTC, nspadaccino submitted a review, later dismissed
Looks good

2024-02-27 14:38 UTC, arpit4ever approved these changes
LGTM

2024-02-28 17:45 UTC, merged