add group id in user response
vinyldns/vinyldns pull request #1328
Opened 2023-11-08 14:00 UTC by Jay07GIT

Fixes #.

Changes in this pull request:
- Added group id in user response
-

2023-11-27 06:27 UTC, Aravindh-Raju requested changes

2023-11-27 06:27 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +    group =  membershipRepo.getGroupsForUser(userId).unsafeRunSync()
We should avoid using `unsafeRunSync()`. Should find a way to get the groups without having to use that.

2023-11-27 06:27 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +  def getGroupByUser(userIdentifier: String, authPrincipal: AuthPrincipal): Result[UserResponseInfo] =
Since we are getting groups we could change the function name to `getGroupForUser`.

2024-01-09 06:00 UTC, Jay07GIT commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +  def getGroupByUser(userIdentifier: String, authPrincipal: AuthPrincipal): Result[UserResponseInfo] =
Changed the name to getUserDetails.

2024-01-09 06:00 UTC, Jay07GIT commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +    group =  membershipRepo.getGroupsForUser(userId).unsafeRunSync()
Removed unsafeRunSync().

2024-01-16 07:37 UTC, Aravindh-Raju reviewed
Test should be added. Looks good otherwise while tested locally!

2024-01-16 07:37 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +    } yield UserResponseInfo(user.id, Some(user.userName), group)
The new function is not covered by tests. Tests for these should be added in `MembershipServiceSpec.scala`.

2024-01-17 07:19 UTC, Jay07GIT commented on modules/api/src/main/scala/vinyldns/api/domain/membership/MembershipService.scala
> +    } yield UserResponseInfo(user.id, Some(user.userName), group)
Added unit tests for `getUserDetails`

2024-02-07 15:42 UTC, nspadaccino approved these changes
Looks good, users route is returning groups list as expected. Would we also be able to add the groups info to the `users/lookupuser` route?

2024-02-20 20:54 UTC, arpit4ever approved these changes
LGTM

2024-02-21 05:56 UTC, Aravindh-Raju approved these changes
LGTM!

2024-02-21 21:14 UTC, merged