updated filter deleted zones using scala to sql query
vinyldns/vinyldns pull request #1329
Opened 2023-11-20 14:00 UTC by Jay07GIT

Fixes #.

Changes in this pull request:
- Updated the code from filter the deleted zones in scala to sql query using where conditions to ignore timeout issue.
-

2023-11-21 07:52 UTC, Aravindh-Raju requested changes
Few changes. Looks good otherwise!

2023-11-21 07:52 UTC, Aravindh-Raju commented on modules/mysql/src/main/resources/db/migration/V3.31__AddZoneChangeFields.sql
> +ADD COLUMN zone_status CHAR(36) NOT NULL;
We can add a new line to mark the EOF as git suggests to make it consistent along all the files.

2023-11-21 07:52 UTC, Aravindh-Raju commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
> +      |
We can remove this line as it isn't necessary so that it aligns with the code structure we followed so far.

2023-11-21 07:52 UTC, Aravindh-Raju commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
> +           |
We can remove this line as well.

2023-11-21 07:52 UTC, Aravindh-Raju commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
> +              zoneNameFilter.map(flt => s"zc.zone_name LIKE '${ensureTrailingDot(flt.replace('*', '%'))}'"),
I'm seeing an Internal Server error while using `*` or zone name ending with `.` in filter (for eg: `ope*` or `open.`). The problem seems to be with `ensureTrailingDot` method. I don't think we need to use this method as everything works fine without that. Also, we need to add `mkString` at the end of the if condition like we have in else for the query to work without error.

Screenshots of the error:
<img width="1904" alt="Screenshot 2023-11-21 at 12 55 05 PM" src="https://github.com/vinyldns/vinyldns/assets/61419792/f7922ffb-9848-4e27-a65b-c5d203ed70c9">
<img width="1904" alt="Screenshot 2023-11-21 at 12 55 11 PM" src="https://github.com/vinyldns/vinyldns/assets/61419792/16d5fe51-b8a0-455e-9b7f-4497728ce107">

2023-11-21 16:17 UTC, Jay07GIT commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
> +              zoneNameFilter.map(flt => s"zc.zone_name LIKE '${ensureTrailingDot(flt.replace('*', '%'))}'"),
Resolved the issue.

2023-11-21 16:18 UTC, Jay07GIT commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
> +           |
Removed the unwanted lines

2023-11-21 16:18 UTC, Jay07GIT commented on modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlZoneChangeRepository.scala
> +      |
Removed the unwanted lines

2024-01-16 19:28 UTC, JoshSEdwards commented on modules/portal/public/lib/controllers/controller.zones.js
> +        myDeleteZonesPaging = pagingService.resetPaging(myDeleteZonesPaging);
Very minor, but can we change this to myDelete**d**ZonesPaging and allDelete**d**ZonesPaging? So it's consistent with everything else.

2024-01-17 07:18 UTC, Jay07GIT commented on modules/portal/public/lib/controllers/controller.zones.js
> +        myDeleteZonesPaging = pagingService.resetPaging(myDeleteZonesPaging);
Updated the name.

2024-01-17 18:53 UTC, nspadaccino approved these changes
LGTM

2024-01-17 19:44 UTC, merged