alignment fix for abandoned zones
vinyldns/vinyldns pull request #1344
Opened 2024-02-20 07:03 UTC by Jay07GIT

Fixes #.

Changes in this pull request:
- Alignment fix for abandoned zones.

2024-02-21 15:03 UTC, nspadaccino approved these changes
LGTM

2024-02-27 20:11 UTC, nspadaccino requested changes
<img width="1728" alt="Screenshot 2024-02-27 at 3 08 47 PM" src="https://github.com/vinyldns/vinyldns/assets/37352107/0811c7ee-977f-4c84-8f2f-9c4dc05dae66">
Still looking mis-aligned for me

2024-03-12 05:32 UTC, Aravindh-Raju requested changes
As Nick mentioned, still mis-aligned for me as well.

2024-03-20 09:00 UTC, Aravindh-Raju requested changes

2024-03-20 09:00 UTC, Aravindh-Raju commented on modules/portal/app/views/zones/zones.scala.html
> +                                            <div class="dataTables_paginate vinyldns_zones_paginate" ng-show="tab == 'myDeletedZones'">
The `ng-show` condition displays the pagination button whenever we are on the tab. But generally, the button needs to show up only when we have reached the pagination limit set.

I looked into the code. We can revert all these changes and just change the following in all occurrences of `myDeletedZones` and `allDeletedZones` pagination html:
```
<div class="dataTables_paginate vinyldns_paginate">
```

We just have to replace `vinyldns_zones_paginate` with `vinyldns_paginate` for the page number to be aligned in `myDeletedZones` and `allDeletedZones`. There is no css class named `vinyldns_zones_paginate` which causes the misalignment.  I think we can revert all other changes made.

2024-03-29 03:49 UTC, Jay07GIT commented on modules/portal/app/views/zones/zones.scala.html
Fixed the issue with tags instead of css changes. Thanks for suggestions.

2024-04-02 13:52 UTC, arpit4ever approved these changes
LGTM

2024-04-23 05:56 UTC, Aravindh-Raju approved these changes
LGTM!

2024-04-23 17:33 UTC, nspadaccino approved these changes
looks good

2024-04-24 15:49 UTC, merged