Ownership transfer for records
vinyldns/vinyldns pull request #1348
Opened 2024-03-01 18:22 UTC by Jay07GIT

Fixes #.

Changes in this pull request:
-
-

2024-03-01 19:39 UTC, Jay07GIT commented
SInce faced unsigned issue in the [PR commit](https://github.com/vinyldns/vinyldns/pull/1229/). Opened this as a new one and closing the existing PR.

2024-03-12 03:48 UTC, nspadaccino requested changes
I noticed a few bugs:

• When the user is part of the shared zone's owner group, the ownership transfer button does not appear on any of the records in the zone
<img width="1728" alt="Screenshot 2024-03-11 at 11 38 04 PM" src="https://github.com/vinyldns/vinyldns/assets/37352107/f1312896-5d76-434f-8e7e-44b625731228">
• Columns look squished on default zoom in web browser (record type and ttl values are running over into two lines)
• Transfer request can be submitted even if no group was chosen
• Once a transfer request has been raised/approved in a zone, record updates in that zone cannot be submitted. When the "Yes" button is clicked, nothing happens
<img width="1728" alt="Screenshot 2024-03-11 at 11 41 21 PM" src="https://github.com/vinyldns/vinyldns/assets/37352107/1dcf780b-e3b9-4c36-aa72-9b8b9d1ac3a6">
• On a record which has had a successful ownership transfer, when you click the update button with a non-owner user, the record owner group box is blank
<img width="1728" alt="Screenshot 2024-03-11 at 11 43 11 PM" src="https://github.com/vinyldns/vinyldns/assets/37352107/c3b196ac-cef5-43c6-8bab-270a667938c8">
• When you go to request an ownership transfer of an owned record, both boxes are blank
<img width="1728" alt="Screenshot 2024-03-11 at 11 45 04 PM" src="https://github.com/vinyldns/vinyldns/assets/37352107/cb1b04a8-8322-49dc-9fc3-172312626412">
•

2024-03-19 13:52 UTC, nspadaccino commented
Tested with the latest code, all my previous comments have been resolved. I found one more bug:

When I go to close an ownership transfer request, the Record Owner Group Status box is blank, and I am able to submit the request without choosing anything.
<img width="1728" alt="Screenshot 2024-03-19 at 9 50 16 AM" src="https://github.com/vinyldns/vinyldns/assets/37352107/c37f33fd-1b7c-445c-b872-077a9e97d0de">

2024-03-29 03:51 UTC, Jay07GIT commented
@nspadaccino Fixed the issue.

2024-04-23 03:10 UTC, arpit4ever submitted a review, later dismissed
Ownership transfer functionality looks good.

2024-04-23 06:46 UTC, Aravindh-Raju approved these changes
Few things to test out in dev env related to email notifier. Looks good otherwise!

2024-04-23 06:46 UTC, Aravindh-Raju commented on modules/api/src/main/resources/reference.conf
> +  notifiers = ["email"]
I don't see this config in `application.conf`. We will have to add it there with the right details as mentioned in the [operator guide](https://www.vinyldns.io/operator/config-api.html#notifiers) before or after deploying for it to work.

2024-04-23 06:46 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
> +        member <- userRepository.getUser(group.map(_.memberIds.head).getOrElse("<none>"))
Just for my clarification, we will always get the first user/member of the group from the previous step here, since we are using `memberIds.head`. So I guess only the first user/member will receive the email. Is this the intended behaviour?

2024-04-23 06:46 UTC, Aravindh-Raju commented on modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
> +        member <- userRepository.getUser(group.map(_.memberIds.head).getOrElse("<none>"))
Same doubt as above here.

2024-04-24 03:10 UTC, nspadaccino commented
Two things I found when testing:
<img width="1728" alt="Screenshot 2024-04-23 at 3 48 25 PM" src="https://github.com/vinyldns/vinyldns/assets/37352107/a217f4ad-9511-44b6-be67-ae74f4ee9ffa">
It looks like the Type and TTL columns don't have enough space

<img width="1728" alt="Screenshot 2024-04-23 at 4 03 13 PM" src="https://github.com/vinyldns/vinyldns/assets/37352107/a11f9a14-aa1c-4de3-b037-0e327b9bcd5f">
This error message should be changed to "Transfer status is required" or something similar

Otherwise all the functionality looks good

2024-08-27 12:21 UTC, Jay07GIT commented on modules/api/src/main/resources/reference.conf
> +  notifiers = ["email"]
Right! . We refers `reference.conf` only, not using email notifier flag from `application.conf`. 
I removed the `email` from `reference.conf`, Since we not use in localhost.

2024-08-27 12:22 UTC, Jay07GIT commented on modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
> +        member <- userRepository.getUser(group.map(_.memberIds.head).getOrElse("<none>"))
This has been intentionally done for test the email. But, I guess we can good to test in dev So, I updated the code as expected.

2024-08-29 12:47 UTC, Jay07GIT commented on modules/api/src/main/scala/vinyldns/api/notifier/email/EmailNotifier.scala
> +        member <- userRepository.getUser(group.map(_.memberIds.head).getOrElse("<none>"))
Answered in above comments.

2024-09-24 18:28 UTC, nspadaccino approved these changes
Looks good, all my previous findings were resolved

2024-09-24 19:47 UTC, arpit4ever approved these changes
LGTM

2024-09-24 20:02 UTC, merged