WIP - Add backend provider
vinyldns/vinyldns pull request #980
Opened 2020-09-16 01:06 UTC by pauljamescleary

Add a backend provider interface and default implementation to talk to DDNS

- Added dynamic loader for a `Backend`
- Added `dns` module that holds the existing `DnsConnection` code
- Added a `DnsBackend` implementation that wraps a `DnsConnection`
- Updated all tests and integration tests to passed
- Added `loadZone` to the `DnsBackend`

**Next up**
- Comments?
- Update the API guts to use `Backend` thingies, including loading.  Continue to make updates as needed to accommodate integration

2020-09-16 01:07 UTC, pauljamescleary commented on modules/core/src/main/scala/vinyldns/core/domain/backend/Backend.scala
> +trait Backend {
👀  This is what matters, all the other stuff is just fluff to get tests to pass and the like

2020-09-16 01:09 UTC, pauljamescleary commented on modules/dns/src/main/scala/vinyldns.dns/DnsBackend.scala
> +class DnsBackend(zoneConnection: ZoneConnection, conn: DnsConnection)
Default DNS backend implementation, right now wraps existing calls for the most part.  The load zone was copy 🍝  from the `DnsZoneViewLoader`

This may evolve a little, trying to limit changes on these methods as those will have a larger impact on integration, but we shall see.

The idea with DnsBackend is that you should have one DnsBackend configured per DNS server you are integrating with.

2020-09-17 14:03 UTC, pauljamescleary commented
I am actually going to make some changes to this tonight.

Seems like a better approach is to have a `BackendResolver` that has a method `Zone => BackendConnection` 

Also, right now we kind of discard the `backendId` when it comes in.  This should be saved on the `Zone` itself.

This will replace `ZoneConnection` as the mechanism for "connecting" to the dns backend.

The `BackendResolver` will be built in `Boot` using the loader / provider that is already in this PR.

2020-09-19 14:39 UTC, pauljamescleary commented on modules/api/src/main/scala/vinyldns/api/backend/dns/DnsConnection.scala
> +
changed this up a few times.  As part of moving the ability to do a zone transfer / zone load into `DnsConnection`, I needed certain info (`SocketAddress`, `TSIG`)

2020-09-19 14:40 UTC, pauljamescleary commented on modules/api/src/main/scala/vinyldns/api/backend/dns/DnsConnection.scala
> +
This is 98% copy/pasta from `DnsZoneViewLoader`

2020-09-19 14:41 UTC, pauljamescleary commented on modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneService.scala
> +    backendRegistry.ids.toList.toResult
the super cool thing about this one line change is that any backend configured in the system will be available in the UI!

2020-09-21 12:56 UTC, pauljamescleary commented on modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala
> +      backendRegistry: BackendRegistry,
You will see this change in a lot of places.  Instead of using "DNS" things, now we use "Backend" things, the refactoring while a little pervasive wasn't too bad (I didn't update tests yet so grain of salt on that)

2020-09-21 12:57 UTC, pauljamescleary commented on modules/api/src/main/scala/vinyldns/api/backend/dns/DefaultDnsBackend.scala
> +
Provides a `DnsBackend` implementation that wraps how we currently do things

2020-09-21 12:59 UTC, pauljamescleary commented on modules/api/src/main/scala/vinyldns/api/backend/dns/DnsBackendProvider.scala
> +    */
Loads DNS backend ids.  The important thing in here is `legacy` support.  The big win there is that this will work without any configuration changes for existing users.

I named it "legacy" because the intent is to move away from it eventually.

This subtle change makes adopting a release with this backend easy (well, existing users do not need to do anything so that's cool)

2020-09-21 13:00 UTC, pauljamescleary commented on modules/api/src/main/scala/vinyldns/api/backend/dns/DnsConnection.scala
> +  def apply(
can ignore this, nothing special right here

2020-09-21 13:01 UTC, pauljamescleary commented on modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneConnectionValidator.scala
> -  def hasSOA(records: List[RecordSet], zone: Zone): Result[Unit] = {
this used to be the check for "does this zone exist", instead we push that behavior to the backend because it will be different for each provider

2020-09-21 13:02 UTC, pauljamescleary commented on modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneViewLoader.scala
> -
moved to `DnsConnection` as it is part of `loadZone` now

2020-09-21 13:03 UTC, pauljamescleary commented on modules/api/src/main/scala/vinyldns/api/engine/RecordSetChangeHandler.scala
> +        Applied(change)
subtle but important changes.  Before the `RecordSetChangeHandler` used to rely on `DnsResponse` to figure out if it should retry.

Now, with this change, it relies on `BackendResponse` to figure out what to do.  

This same logic of retry was moved to `DnsConnection.applyChange`

2020-09-21 13:04 UTC, pauljamescleary commented on modules/core/src/main/scala/vinyldns/core/domain/Fqdn.scala
> +
added some nice helpers into Fqdn.  We have code that tries to sort through combining and splitting record and zone names.  I put it all here as that is where it makes sense.  Route53 turns out relies more on FQDN things than DNS

2020-09-21 13:05 UTC, pauljamescleary commented on modules/core/src/main/scala/vinyldns/core/domain/backend/BackendConnection.scala
> +  */
The workhorse of the backend providers

2020-09-21 13:06 UTC, pauljamescleary commented on modules/core/src/main/scala/vinyldns/core/domain/record/RecordData.scala
> +import scala.util.Try
added a lot of convenience helpers and such here as well, in general these are universally useful and we can start taking advantage of them elsewhere.  Right now, used mostly in Route 53

2020-09-21 13:07 UTC, pauljamescleary commented on modules/r53/src/it/scala/vinyldns/route53/backend/Route53IntegrationSpec.scala
> +class Route53IntegrationSpec
Here is the only test I did.  tbh, could be more exhaustive but it tests a lot of scenarios for integration with Route 53 so I am pretty happy with the coverage it will provide.

2020-09-21 13:08 UTC, pauljamescleary commented on modules/r53/src/main/scala/vinyldns/route53/backend/Route53BackendConnection.scala
> +class Route53BackendConnection(
The meat and potatoes for the Route 53 provider

2020-09-21 13:09 UTC, pauljamescleary commented on modules/r53/src/main/scala/vinyldns/route53/backend/Route53BackendConnection.scala
> +      hostedZoneId <- lookupHostedZone(zoneName)
Important: this will return an empty list if the zone is not found.  This is consistent with how things work with DNS in VinylDNS today

2020-09-21 13:11 UTC, pauljamescleary commented on modules/r53/src/main/scala/vinyldns/route53/backend/Route53BackendConnection.scala
> +  def loadZone(zone: Zone, maxZoneSize: Int): IO[List[RecordSet]] = {
The intent here is to load ALL record sets in the zone.

This is not memory safe, but neither is the rest of Vinyl right now.

Route 53 provides up to 100 records in a single ListResourceRecordSetsRequest, and provides a means to know if there are more records.  Here we recurse until `isTruncated` is false

2020-09-21 13:12 UTC, pauljamescleary commented on modules/r53/src/main/scala/vinyldns/route53/backend/Route53BackendProvider.scala
> +class Route53BackendProvider extends BackendProvider {
pretty simple, just loads any pre-configured connections.

2020-09-21 13:12 UTC, pauljamescleary commented on modules/r53/src/main/scala/vinyldns/route53/backend/Route53Conversions.scala
> +trait Route53Conversions {
buncho helpers for converting from/to vinyldns/route53 things.  I crated a `Conversions` as it follows precedent laid down by `DnsConversions`

2020-09-23 01:01 UTC, pauljamescleary commented
Considering this good to go now.  

1. Did some final "renaming" that I am happier with
2. Updated _all_ tests and integration tests (everything passes)
3. All functional tests pass

2020-09-23 18:58 UTC, remerle commented
I haven't had a chance to go through all of the code, but your description for the PR describes the implementation exactly as I would imagine it would be implemented. It seems like a pretty standard plugin pattern - _"define a contract and any number of implementations can be provided dynamically through config"_.

Hopefully @clinedome can get some 👀 on this.

2020-09-23 19:20 UTC, pauljamescleary commented
@remerle - that is exactly the idea.  The concepts are significant, even if some of the initial implementation is naive:

1. `BackendResolver` - allows VinylDNS to have mechanisms of selecting a backend to send a request to
2. `BackendProvider` - allows a specific backend to decide how or if it will service a request
3. `Backend` - the meat and potatoes once a backend is chosen

Everything else is config or loading.  The dynamic loading using `Class.forName` obviates the need for something like spring, plus it is consistent with the way we do dynamic loading via config in the rest of the system.

2020-09-24 13:32 UTC, nimaeskandary commented on modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneConnectionValidator.scala
> +        IO(Left(ConnectionFailed(zone, "SOA Record for zone not found")))
Are there reasons for a backend to fail finding a zone other than `SOA Record for zone not found`? Cant think of any but maybe this error message could come from the provider

2020-09-24 13:51 UTC, nimaeskandary commented on modules/r53/src/main/scala/vinyldns/route53/backend/Route53Backend.scala
> +        hzid.substring(lastSlash + 1)
would a `substring(lastslash).dropLeft` be safer here?

2020-09-24 14:05 UTC, nimaeskandary requested changes
Had a couple minor comments, this is super cool, being able to use vinyl with other providers is an awesome upgrade 🥇  🥳

2020-09-25 13:24 UTC, pauljamescleary commented on modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneConnectionValidator.scala
> +        IO(Left(ConnectionFailed(zone, "SOA Record for zone not found")))
@nimaeskandary good catch, this is me being lazy before I updated the unit and func tests.  I can change the description.

2020-09-25 13:25 UTC, pauljamescleary commented on modules/r53/src/main/scala/vinyldns/route53/backend/Route53Backend.scala
> +        hzid.substring(lastSlash + 1)
Hmm, maybe, let me test that out

2020-09-25 13:38 UTC, pauljamescleary commented on modules/r53/src/main/scala/vinyldns/route53/backend/Route53Backend.scala
> +        hzid.substring(lastSlash + 1)
I don't see a `dropLeft`, the format of the hosted zone id is `/hostedzone/Z111111QQQQQQQ`

2020-09-25 18:24 UTC, nimaeskandary commented on modules/r53/src/main/scala/vinyldns/route53/backend/Route53Backend.scala
> +        hzid.substring(lastSlash + 1)
Ah my bad thought they had a helper like that. If thats the format then 👍

2020-09-25 18:24 UTC, nimaeskandary approved these changes

2020-09-30 12:57 UTC, remerle approved these changes
LGTM

2020-09-30 13:17 UTC, merged